package com.chonkcheck.android.domain.model

data class Food(
    val id: String,
    val name: String,
    val brand: String?,
    val barcode: String?,
    val servingSize: Double,
    val servingUnit: ServingUnit,
    val servingsPerContainer: Double?,
    val calories: Double,
    val protein: Double,
    val carbs: Double,
    val fat: Double,
    val fiber: Double?,
    val sugar: Double?,
    val sodium: Double?,
    val saturatedFat: Double?,
    val transFat: Double?,
    val cholesterol: Double?,
    val addedSugar: Double?,
    val vitaminA: Double?,
    val vitaminC: Double?,
    val vitaminD: Double?,
    val calcium: Double?,
    val iron: Double?,
    val potassium: Double?,
    val type: FoodType,
    val source: FoodSource?,
    val verified: Boolean,
    val promotionRequested: Boolean,
    val overrideOf: String?,
    val imageUrl: String?,
    val createdAt: Long
)

data class CreateFoodParams(
    val name: String,
    val brand: String?,
    val barcode: String?,
    val servingSize: Double,
    val servingUnit: ServingUnit,
    val servingsPerContainer: Double?,
    val calories: Double,
    val protein: Double,
    val carbs: Double,
    val fat: Double,
    val fiber: Double?,
    val sugar: Double?,
    val sodium: Double?,
    val saturatedFat: Double?,
    val transFat: Double?,
    val cholesterol: Double?,
    val addedSugar: Double?,
    val imageUrl: String?
)

data class UpdateFoodParams(
    val name: String?,
    val brand: String?,
    val barcode: String?,
    val servingSize: Double?,
    val servingUnit: ServingUnit?,
    val servingsPerContainer: Double?,
    val calories: Double?,
    val protein: Double?,
    val carbs: Double?,
    val fat: Double?,
    val fiber: Double?,
    val sugar: Double?,
    val sodium: Double?,
    val saturatedFat: Double?,
    val transFat: Double?,
    val cholesterol: Double?,
    val addedSugar: Double?,
    val imageUrl: String?
)
